services:
  web:
    restart: unless-stopped
    build: ./web
    ports:
      - 4000:4000
  api:
    restart: unless-stopped
    build: ./api
    ports:
      - 3000:3000
    environment:
      MONGDB_URI: mongodb://database/docker-compose-studies
  database:
    restart: unless-stopped
    image: mongo
    ports:
      - 5000:27017
    volumes:
      - docker-compose-studies:/data/db
volumes:
  docker-compose-studies:
